# Default settings for all environments
app:
  name: "Ruby on Rails Tutorial Sample App"
  version: "1.0.0"
  author: "Thao"
  description: "A sample application for learning Rails"

# I18n settings
i18n:
  default_locale: :en
  available_locales:
    - :en
    - :vi

# External links
external_links:
  rails_tutorial_help: "http://www.railstutorial.org/help"
  rails_tutorial_book: "http://www.railstutorial.org/book"
  rails_tutorial_contact: "https://www.railstutorial.org/contact"

# UI settings
ui:
  show_debug_info: false

# Model settings
models:
  micropost:
    content_max_length: 140
    image_content_types:
      - "image/jpeg"
      - "image/gif"
      - "image/png"
    image_size_limit: 5 # 5MB
    image_display_width: 250
    image_display_height: 250

  user:
    name_max_length: 50
    email_max_length: 255
    valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    year_of_past: 100
    password_min_length: 6
    remember_me: "1"
    avatar_size: 80
    reset_token_expiration: 2
    show_followers_limit: 6
# Body class settings
body_class:
  users:
    new_page: "user-new-page"
    show_page: "user-show-page"
    edit_page: "user-edit-page"
    index_page: "user-index-page"
    follow_page: "user-follow-page"

  sessions:
    new_page: "session-new-page"

  password_resets:
    new_page: "password_resets-new-page"
    edit_page: "password_resets-edit-page"

  static_pages:
    home_page: "static_pages-home-page"

# Pagy settings
pagy:
  show_check_count: 1
  items: 10
  size: [1, 4, 4, 1] # [left_gap, left_pages, right_pages, right_gap]

# Page settings
page:
  users:
    edit:
      avatar_path: "http://gravatar.com/emails"

# Email settings
email:
  from_address: "hosithao1622004@gmail.com"
