# Development specific settings
ui:
  show_debug_info: true

# Database settings
database:
  pool_size: 5
  timeout: 5000

# Mailer settings
user_mailer:
  authentication_method: "plain"
  address: "smtp.gmail.com"
  port: 587
  host: "localhost:3000"
  protocol: "http"
